.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. starwels_qt test_starwels_qt
clean: FORCE
	$(MAKE) -C .. starwels_qt_clean test_starwels_qt_clean
check: FORCE
	$(MAKE) -C .. test_starwels_qt_check
starwels-qt starwels-qt.exe: FORCE
	 $(MAKE) -C .. starwels_qt
